http:
  host: 'localhost'
  port: 3000
db:
  mongo:
    type: 'mongodb'
    host: 'localhost'
    port: 27017
    username: 'root'
    password: 'example'
    database: 'test'
    synchronize: true
    useUnifiedTopology: true
  mysql:
    type: 'mysql'
    host: 'localhost'
    port: 3306
    #username: 'root'
    username: 'root'
    #password: 'my-secret-pw'
    password: 'example'
    database: 'test'
    synchronize: true
keycloak:
  authServerUrl: 'http://localhost'
  realm: 'master'
  clientId: 'Blank-nestjs'
  secret: 'ha9f7HGcztgCjwGdB54tN8IJhjRsFIzH'
mail:
  host: 'smtp.gmail.com'
  port: 465
  user: ''
  password: ''
  from: ''
  mailTransport: ''



#MAIL_HOST=
#MAIL_USER=user@example.com
#MAIL_PASSWORD=topsecret
#MAIL_FROM=noreply@example.com

# optional
#MAIL_TRANSPORT=smtp://${MAIL_USER}:${MAIL_PASSWORD}@${MAIL_HOST}