http:
  host: '192.168.1.139'
  port: 81
db:
  mongo:
    type: 'mongodb'
    host: '192.168.1.139'
    port: 27017
    username: 'root'
    password: 'example'
    database: 'test'
    synchronize: true
    useUnifiedTopology: true
  mysql:
    type: 'mysql'
    host: '192.168.1.139'
    port: 3306
    #username: 'root'
    username: 'root'
    #password: 'my-secret-pw'
    password: 'example'
    database: 'test'
    synchronize: true
keycloak:
  authServerUrl: 'http://192.168.1.139/'
  realm: 'master'
  clientId: 'blank-nestjs'
  secret: '0YTxRYqMPVi0cBRtizkeRUSBipoS08JB'
mail:
  host: 'smtp.example.com'
  user: ''
  password: ''
  from: ''
  mailTransport: ''
