http:
  host: 192.168.1.114
  port: 3000
db:
  mongo:
    type: 'mongodb'
    host: 192.168.1.114
    port: 27017
    username: 'root'
    password: 'example'
    database: 'test'
    synchronize: true
    useUnifiedTopology: true
  mysql:
    type: 'mysql'
    host: 192.168.1.114
    port: 3306
    #username: 'root'
    username: 'root'
    #password: 'my-secret-pw'
    password: 'example'
    database: 'test'
    synchronize: true
keycloak:
  authServerUrl: 192.168.1.114
  realm: 'master'
  clientId: 'Blank-nestjs'
  secret: 'ha9f7HGcztgCjwGdB54tN8IJhjRsFIzH'
mail:
  host: 'smtp.example.com'
  user: ''
  password: ''
  from: ''
  mailTransport: ''
