http:
  host: 'localhost'
  port: 3000

db:
  mysql:
    type: 'mysql'
    host: 'localhost'
    port: 3306
    username: 'root'
    password: 'my-secret-pw'
    database: 'test'
    synchronize: true
  mongo:
    type: 'mongodb'
    host: 'localhost'
    port: 27017
    username: 'root'
    database: 'test'
    synchronize: true
    useUnifiedTopology: true